create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Jewellery',
  price numeric not null,
  original_price numeric,
  description text default '',
  meesho_link text not null,
  image text default '',
  badge text default '',
  available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- The Vercel API uses the Supabase service-role key, so browser clients do not need direct table access.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in VITE_ variables.
